### ISSUE TITLE
move config.json to the data repo 

### ISSUE THREAD

**Issue by bstabler** [RSGInc/ActivityViz#224]
so there are no potential conflicts when pulling in updates to forked repos

**Comment by medailey** [comment]
I can do this, but we need someplace or some file that then points to where the utility can find the config.json.  As it stands without the config.json the utility has nothing to load and no where to look. We would have to hard code a location for it to find it or a default location in the HTML files.

**Comment by bstabler** [comment]
yeah...I guess we leave it like this for now.  Thanks.
