### ISSUE TITLE
file:\\ URL in config.json

### ISSUE THREAD

**Issue by steventrev** [RSGInc/ActivityViz#225]
I'm testing local scenario data on Windows. I have been unable to use the file:\\ URL convention in config.json.

Local and relative to the repository does work:
`"datalocation":  "/data/rsginc/"`

The file:\\ URL to the same path does not:
`"datalocation":  "file:///C:/ActivityViz/data/rsginc/"`

**Comment by medailey** [comment]
Hey Steven if you want to use the data locally, you have to put the data in the same directory as the ActivityViz itself. So if you have the tool in C:\ActivityViz the data needs to be in C:\ActivityViz\data.
The config.json then has to use the localhost web address to find the files like this:
"datalocation":"http://localhost:63342/ActivityViz /data/rsginc/"

The reason being is that the files are access and served up via a web server on your machine. The files themselves have no access to your local file system. The port your localhost uses may differ from the example above.  Let me know if this doesn't work for you.

**Comment by steventrev** [comment]
Thanks, Michael - I suspected as much. This does slightly complicate an "offline" instance of mating the ActivityViz and ActivityViz_Data repos.

To clarify, the relative path of just `"datalocation": "/data/rsginc/"` does work correctly and would avoid potential port mismatches.

I'll submit a PR to add a localhost example in the readme.
