### ISSUE TITLE
various UI clean-ups for consistency, formatting, etc.

### ISSUE THREAD

**Issue by bstabler** [RSGInc/ActivityViz#242]
These are captured in [aviz-clean-up.pptx](https://github.com/RSGInc/ActivityViz/files/4098959/aviz-clean-up.pptx).   Slides 2 and 3 are improved versions of the BarChart and Map and 3D Map.

**Comment by ryanstreur** [comment]
- [ ] Add white space above tab titles
- [ ] Move focus color and HMC color to config file
  - [ ] Add each HMC as a layer if feature is enabled
- [ ] Refactor CSS styles to use consistent styles for common elements.
- [ ] Change "Person Type and Purpose" to bold in the Time Use area graph
- [ ] Change "Focus Color:" label to bold in Scenario Travel Model for Base Year 2010 in ARC Transportation Planning Scenario Travel Model for Base Year 2010 > Trip ODs
- [ ] Metro MCEVIZ Scenario Freight > Freight Flows
  - [ ] Remove colon from "Filter:" label, make bold.
  - [ ] Make "Color" label bold

**Comment by ryanstreur** [comment]
#243

**Comment by ryanstreur** [comment]
#243 opened against this issue
