### ISSUE TITLE
Tampa Visualizer Feedback - Remaining updates

### ISSUE THREAD

**Issue by ryanstreur** [RSGInc/ActivityViz#304]
Checked means it's deployed to [this gh-pages site](https://ryanstreur.github.io/ActivityViz)

- [x] Enable user to configure custom values for titles of individual visuals - **done for Tampa, add custom titles to other visuals out-of-scope**
- [x] Sunburst Chart
  - [x] CSV header appearing in data table in middle of data.
- [x] TimeUse chart
  - [x] Add config options to hide the Counts/Percentages" toggle. See comment below for config values.
  - [x] Change "Stacked/Expanded" to "Counts/Percentages"

--- PR Here --- 
- [x] Notify @goreaditya after PR resolved
- [x] Sunburst Chart - Hover issue, see [comment below.](https://github.com/RSGInc/ActivityViz/issues/304#issuecomment-622200506)
- [x] TimeUse Chart
  - [x] Y Axis - max label issue in "Stacked" view
  - [x] Legend entries activate on click instead of on hover.
  - [x] Legend color should match chart colors exactly - since they do match the chart color exactly when the user hovers over the chart, we may want to skip this for now.
- [x] Grouped Bar Chart
  - [x] Group label rotation - vertical group labels on the X Axis should be configurable to be horizontal

**Comment by ryanstreur** [comment]
Configuration to add to TimeUse

```
displayCountsByDefault
displayPercentagesByDefault
hideCountsPercentagesToggle
```

**Comment by goreaditya** [comment]
@ryanstreur there are some issues in the sunburst chart. Here are Orian's comments
"some strange things are happening with the hover-over: when I hover over certain categories (e.g. carpool), that category shows in it's original color on the graph and everything else fades (correct behavior), but for other categories (e.g. drive alone) all categories including the one I hover over fade.  I still see the hover-over pop-up box but it's harder to be sure which color I'm hovering over."
For e.g. on Drive Alone every color is faded and no display on the side.
![image](https://user-images.githubusercontent.com/14181592/80773074-c64a5600-8b26-11ea-9b7f-693b1d1b332b.png)
For Other, everything but Other is faded and display of percentage and count on the side.
![image](https://user-images.githubusercontent.com/14181592/80773055-b468b300-8b26-11ea-9b68-64632cf282dd.png)

Can you fix this as soon as you can?
